// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalServicesWebApi.Context;

#nullable disable

namespace RentalServicesWebApi.Migrations
{
    [DbContext(typeof(RentalContext))]
    [Migration("20220420092244_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RentalServicesWebApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.CollectingMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MeansOfCollection")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeetingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CollectingMethods");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RentalInfoSystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalInfoSystemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.RentalInfoSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CollectingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentingDateInfoResId")
                        .HasColumnType("int");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<int?>("UserNameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectingId");

                    b.HasIndex("RentingDateInfoResId");

                    b.HasIndex("UserNameId");

                    b.ToTable("RentalInfoSystems");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.RentalSetUp", b =>
                {
                    b.Property<int>("ResId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResId"), 1L, 1);

                    b.Property<string>("BookingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResId");

                    b.ToTable("RentalSetUps");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MobileNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.Category", b =>
                {
                    b.HasOne("RentalServicesWebApi.Models.Item", null)
                        .WithMany("Category")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.Item", b =>
                {
                    b.HasOne("RentalServicesWebApi.Models.RentalInfoSystem", null)
                        .WithMany("Items")
                        .HasForeignKey("RentalInfoSystemId");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.RentalInfoSystem", b =>
                {
                    b.HasOne("RentalServicesWebApi.Models.CollectingMethod", "Collecting")
                        .WithMany()
                        .HasForeignKey("CollectingId");

                    b.HasOne("RentalServicesWebApi.Models.RentalSetUp", "RentingDateInfo")
                        .WithMany()
                        .HasForeignKey("RentingDateInfoResId");

                    b.HasOne("RentalServicesWebApi.Models.User", "UserName")
                        .WithMany()
                        .HasForeignKey("UserNameId");

                    b.Navigation("Collecting");

                    b.Navigation("RentingDateInfo");

                    b.Navigation("UserName");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.Item", b =>
                {
                    b.Navigation("Category");
                });

            modelBuilder.Entity("RentalServicesWebApi.Models.RentalInfoSystem", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
